version: "3"

services:
  deu-role-auth:
    build:
      context: .
      dockerfile: Dockerfile
    image: deu-role-auth:latest
    restart: always
    env_file:
      - .env
    environment:
      - WATCH_FILES=${WATCH_FILES}
      - DEBUG=${DEBUG}
    volumes:
      - .:/go/src/app
    networks:
      - shared-services

networks:
  shared-services:
    external: true
